In [1]:
import osc
import numpy as np

from scipy.sparse import csgraph
from scipy.sparse.linalg import eigsh

In [2]:
def get_num_clusters(A):
    L = csgraph.laplacian(A, normed=True)
    n_components = A.shape[0]

    eigenvalues, eigenvectors = eigsh(L, k=n_components, which = 'LM', sigma = 1.0, maxiter=5000)


    index_lagest_gap = np.argmax(np.diff(eigenvalues))
    nb_clusters = index_lagest_gap+1

    return nb_clusters
    

In [3]:
# a column wise dataset of samples
X = np.reshape(np.array(range(1,26)), (5,5))

In [4]:
X = np.array([[ .1,  2,  .2,  4,  5],
       [ .15,  7,  .19,  9, 10],
       [.09, 12, .21, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
X

array([[ 0.1 ,  2.  ,  0.2 ,  4.  ,  5.  ],
       [ 0.15,  7.  ,  0.19,  9.  , 10.  ],
       [ 0.09, 12.  ,  0.21, 14.  , 15.  ],
       [16.  , 17.  , 18.  , 19.  , 20.  ],
       [21.  , 22.  , 23.  , 24.  , 25.  ]])

In [6]:
lambda_1 = 0.099
lambda_2 = 0.001



diagconstraint = False
max_iterations = 200
mu = .1

In [7]:
osc_model = osc.osc(max_iterations, lambda_1, lambda_2, mu, diagconstraint)

In [8]:
A = osc_model.osc_exact(X)

In [12]:
xn = A.shape[0]

In [14]:
R = np.triu(np.ones((xn, xn-1)),1) - np.triu(np.ones((xn, xn-1))) + np.triu(np.ones((xn, xn-1)),-1) - np.triu(np.ones((xn, xn-1)))
R

array([[-1.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.],
       [ 0.,  1., -1.,  0.],
       [ 0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
np.matmul(A,R)

array([[-0.44215863,  0.43877377, -0.44998219,  0.        ],
       [ 0.34378408, -0.34378408,  0.24369802, -0.00258028],
       [-0.43424344,  0.43708308, -0.44991916,  0.        ],
       [ 0.28234553, -0.28234553,  0.31591377,  0.00050588],
       [ 0.25213665, -0.25213665,  0.34146844,  0.00178714]])

In [23]:
from scipy.spatial.distance import pdist

In [27]:
pdist(A)

array([0.79759558, 0.00649509, 0.82550826, 0.83695708, 0.79332239,
       0.12107925, 0.16849464, 0.82150204, 0.83306495, 0.0478099 ])